# Generated by Django 2.0.2 on 2023-04-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(default='', max_length=20, verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_brief',
            field=models.CharField(default='暂无商品简介', max_length=256, verbose_name='商品简介'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_desc',
            field=models.CharField(default='', max_length=256, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='goods',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='市场价格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='购买价格'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.GoodsSKU', verbose_name='商品'),
        ),
    ]
