# Generated by Django 2.0.2 on 2023-04-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20230402_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='分类代码')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
                ('category_type', models.SmallIntegerField(default=1, verbose_name='商品分类代号')),
            ],
            options={
                'verbose_name': '商品类目',
                'verbose_name_plural': '商品类目',
                'db_table': 'df_goods_category',
            },
        ),
    ]
